Add accounts lifecycle
sequinstream/sequin pull request #364
Opened 2024-10-08 20:47 UTC by thisisgoldman

2024-10-08 20:47 UTC, thisisgoldman commented
* **#364** <a href="https://app.graphite.dev/github/pr/sequinstream/sequin/364?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @thisisgoldman and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-08 21:48 UTC, acco commented on assets/package.json
> +    "cmdk-sv": "^0.0.18",
did this come in via shadcn?

2024-10-08 21:48 UTC, acco commented on assets/svelte/components/Sidenav.svelte
> +  import { createEventDispatcher } from "svelte";
Claude likes these, but we almost always want to avoid them. Looks like it's unused?

Can you please remove all unused from all JS files? You can do CMD+. and select 'delete unused'

2024-10-08 21:48 UTC, acco commented on assets/svelte/components/Sidenav.svelte
> +    });
Hmm... do you need the tick because `triggerId` is not visible while settingsCommand is open?

2024-10-08 21:48 UTC, acco commented on assets/svelte/components/Sidenav.svelte
> +    closeAndFocusTrigger(accountId);
this is the only user of this function. Why not just collapse the function into this one?

2024-10-08 21:48 UTC, acco commented on assets/package.json
> +    "cmdk-sv": "^0.0.18",
Looks like that's so 👍

2024-10-08 21:48 UTC, acco commented on assets/svelte/settings/AccountSettings.svelte
> +  }
Are these unused?

2024-10-08 21:48 UTC, acco commented on assets/svelte/settings/AccountSettings.svelte
> +  export let selected_account: Account;
This is minor, as we mix elsewhere. But new thing is trying to make sure backend camelizes for the frontend.

Can be skipped where inconvenient

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/account.ex
> +  alias Sequin.Accounts.UserAccount
!Important

This should be `AccountUser` and table `account_users`. It's conventional in join tables to sort them alphabetically.

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +             %User{current_account_id: account.id}
The troubling part with this pattern is that we're storing important data (accounts a user has access to) in _two_ places:

1. `account_users`
2. `users.current_account_id`

This means we have to manage lifecycle in two places whenever a user is removed from an account or an account is destroyed.

The join model also means we no longer have enforcement that `current_account_id` is in a user's list of `account_users`. I'm afraid this leaves open big potential for error: without enforcement, either we need to be *perfect* about managing both tables simultaneously or we need to be *perfect* about now relying on `current_account_id` exclusively to determine what a user has access to – no bueno.

I see two paths forward:

**PG trigger funcs**
This is a perfect use case for moving enforcement down to a PG trigger function:

- Whenever a user is inserted or updated, and `current_account_id` is changing, we verify the user has access by checking `account_users`:

```sql
create or replace function verify_user_access()
returns trigger as $$
begin
    if not exists (
        select 1
        from account_users
        where user_id = new.id
        and account_id = new.current_account_id
    ) then
        raise exception 'User does not have access to the specified account';
    end if;
    return new;
end;
$$ language plpgsql;

create trigger check_user_access
before insert or update of current_account_id on users
for each row
when (old.current_account_id is distinct from new.current_account_id)
execute function verify_user_access();
```

- Whenever `account_users` is updated or deleted, we verify corresponding affected users have their `current_account_id` unset:

```
sql
create or replace function unset_current_account()
returns trigger as $$
begin
    if tg_op = 'delete' then
        update users
        set current_account_id = null
        where id = old.user_id
        and current_account_id = old.account_id;
    elsif tg_op = 'update' then
        if old.user_id != new.user_id or old.account_id != new.account_id then
            update users
            set current_account_id = null
            where id = old.user_id
            and current_account_id = old.account_id;
        end if;
    end if;
    return null;
end;
$$ language plpgsql;

create trigger unset_current_account_on_change
after update or delete on account_users
for each row
execute function unset_current_account();
```

btw - **We should consider generally having a trigger that prevents account_id from changing on accounts_users** like when would we want that to happen? 

It would be nice to have Postgres-level tests for this! i.e. use factories to insert stuff, and then run a `Postgrex.query` directly to change the database, and verify Postgres rebuffs bad changes.

**Add an attribute to the join model**
Alternatively – and more simply? – you can simply add a column to the join model, `current (boolean)`. Then, you can have a unique index on user_id + account_id + default where current=true. That will prevent you from having more than one default. You can transactionally "swap" the default when the user changes their selection.

```
create unique index idx_account_users_current
on account_users (user_id, account_id, current)
where current = true;
```

To find the user's current account, it just requires an extra step. But the isolation of the association to one location is probably worth it?

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      end)
I think it's fine to leave it unset? What happens in that case?

I can imagine that the app simply sets it on load the next time they come through.

In general, I think we should plan on users not having a current account, and dynamically deal with that in our LiveView UserAuth plug? vs always ensuring it's set.

In fact, we could just assume the first account in `account_users` (ordered by account_id asc or whatever) is the current, unless overwritten by a boolean on another entry.

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      end)
I imagine we can isolate this in one location in `User`:

```
def current_account(%User{} = user) do
  # preloads `accounts_users`
  # find account where current = true or grab the first with `order by account_id asc`
end
```

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/user_account.ex
> +  typed_schema "users_accounts" do
accounts_users

2024-10-08 21:48 UTC, acco commented on lib/sequin/accounts/user_account.ex
> +    timestamps(updated_at: false)
if adding `current`, the table will be updatable 

as stated elsewhere, we can use a PG trigger to prevent account_id or user_id from ever being modified

2024-10-08 22:02 UTC, thisisgoldman commented on assets/svelte/components/Sidenav.svelte
> +  import { createEventDispatcher } from "svelte";
> You can do CMD+. and select 'delete unused'

What is this magic - can you explain?

2024-10-08 22:02 UTC, thisisgoldman commented on assets/svelte/components/Sidenav.svelte
> +    });
I might have made this work without this function. Good call out.

2024-10-08 22:04 UTC, thisisgoldman commented on assets/svelte/settings/AccountSettings.svelte
> +  export let selected_account: Account;
Got it

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        Repo.transaction(fn ->
`Repo.transact`

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        Repo.transaction(fn ->
you may need an ok tuple

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/account_user.ex
> +    |> cast(attrs, [:user_id, :account_id, :current])
remove user_id and account_id from cast

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/account_user.ex
> +    |> unique_constraint([:user_id, :account_id, :current])
remove this - we want to blow up

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/account_user.ex
> +  def changeset(account_user, attrs) do
create_changeset

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/account_user.ex
> +  def changeset(account_user, attrs) do
or just changeset, remove update_changeset

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      nil -> {:error, :not_found}
{:error, Error.not_found(entity: :account, params: %{ user_id: user_id, account_id: account_id })}

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      {:error, :last_account}
```suggestion
      {:error, Error.invariant(message: "cannot delete ..." )}
```

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +          {:error, _} -> {:error, :not_found}
Error.not_found

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        {:error, :not_found}
Error.not_found

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +          User |> Repo.get(user_id) |> Repo.preload([:accounts_users, :accounts])
do we have a get_user or something we can use?

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +          User |> Repo.get(user_id) |> Repo.preload([:accounts_users, :accounts])
Add preloads as an arg to the get_user function and use that. See examples elsewehre by looking for "preloads" arg

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        {:error, :not_found}
Error.not_found

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        case Repo.delete(account_user) do
I don't think this can return an error

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/user.ex
> +  def current_account(_), do: nil
remove this

2024-10-09 22:45 UTC, acco commented on lib/sequin/accounts/user.ex
> +  def current_account(user) when is_map(user) do
```suggestion
  def current_account(%User{} = user) do
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +  end
remove

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +
Add `@impl`

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +    {:ok, new_account} = Accounts.get_account_for_user(user.id, new_account_id)
```suggestion
    user = current_user(socket)
    account = Sequin.Enum.find!(user.accounts, & &1.id == new_account_id)
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +  def handle_event("change_selected_account", %{"accountId" => new_account_id}, socket) do
```suggestion
  def handle_event("change_selected_account", %{"accountId" => account_id}, socket) do
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +         |> assign(current_account: new_account)
i think we'll remove this

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +    user = socket.assigns.current_user
use current_user/1

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +         |> assign(current_account: new_account)
remove this

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +      {:ok, account}
```suggestion
         {:ok, user} <- Accounts.set_current_account_for_user(user.id, account.id) do
      {:ok, user}
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +      {:ok, new_account} ->
```suggestion
      {:ok, user} ->
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +         |> assign(current_user: %{user | accounts: updated_account_list})
```suggestion
         |> assign(current_user: user)
```

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +      <%= if @current_user do %>
remove

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +    <div>
remove

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/consumers/index.ex
> +    account = User.current_account(user)
go through socket for this

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/http_endpoints/form.ex
> +        {:ok, api_token} = ApiTokens.get_token_by(account_id: current_account_id(socket))
revert

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +  end
def mount(_params, _session, socket) do
  {:ok, socket}
end

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +    {:ok, new_account} = Accounts.get_account_for_user(user.id, new_account_id)
current_user/1
Sequin.Enum.find!

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +    {:ok, account} = Accounts.get_account_for_user(user.id, account_id)
ditto above

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:noreply, push_navigate(socket, to: socket.assigns.current_path)}
Use the Accounts.get_user thing again to reload the user (with preloads) and put back in assigns

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +    {:ok, account} = Accounts.get_account_for_user(user.id, account_id)
ditto above

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +         |> assign(current_account: new_account)
delete

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +    assigns = assign(assigns, :parent_id, "account_settings")
assign(assigns, :current_account, User.current_account(assigns.current_user)

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/user_auth.ex
>      if user = user_token && Accounts.get_user_by_session_token(user_token) do
get_user_by_session_token shoudl do the preloads

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/user_auth.ex
> +      user = Sequin.Repo.preload(user, :accounts)
remove

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/user_auth.ex
> +            |> assign(:current_account, current_account)
remoev

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/user_auth.ex
> +        |> assign(:current_account, current_account)
remove

2024-10-09 22:45 UTC, acco commented on lib/sequin_web/user_auth.ex
> +      |> assign(:current_account, nil)
remove

2024-10-09 22:45 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +           )
```suggestion
    create unique_index(:accounts_users, [:user_id, :current],
             prefix: @config_schema,
             where: "current = true",
             name: "idx_users_current"
           )
```

2024-10-09 22:45 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +    end
put this in a different merge/deploy

2024-10-09 22:45 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +    end
remove

2024-10-09 22:45 UTC, acco commented on test/sequin/accounts_test.exs
> +      assert {:error, :not_found} = Accounts.set_current_account_for_user(user_1.id, account_for_user_2.id)
%Error.NotFoundError{}

2024-10-09 22:45 UTC, acco commented on test/sequin/accounts_test.exs
> +      assert {:error, :not_found} = Accounts.associate_user_with_account(user, account)
not_found

2024-10-09 22:45 UTC, acco commented on test/sequin/accounts_test.exs
> +      assert Accounts.get_account_for_user(user.id, account.id) == {:error, :not_found}
not_found

2024-10-09 22:45 UTC, acco commented on test/sequin/accounts_test.exs
> +      assert Accounts.get_account_for_user(user.id, account.id) == {:ok, account}
```suggestion
      assert  {:ok, ^account} = Accounts.get_account_for_user(user.id, account.id) =
```

2024-10-10 02:32 UTC, thisisgoldman commented on assets/svelte/components/Sidenav.svelte
> +            <Button
Continuing to use the <Button> component for now as triggering the popover using a plain <button> is not obvious. Marking as a todo for another rev on this element

2024-10-10 02:33 UTC, thisisgoldman commented on assets/svelte/components/ui/button/index.ts
> +      settings: "w-full flex flex-row justify-start text-muted hover:text-basis hover:bg-canvasSubtle",
Keeping as <Button> for now as the switch to <button> is not obvious.

2024-10-10 02:36 UTC, thisisgoldman commented on lib/sequin/accounts/accounts.ex
> +  def delete_account_and_account_resources(%Account{} = account, delete_users \\ false) do
Combined - made the ability to delete all users an optional argument

2024-10-10 02:38 UTC, thisisgoldman commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
Made users.account_id nullable. We can remove in a migration in another PR:

- _# 4. Add back the account\_id column_

  alter table(:users, prefix: @config\_schema) do

  add :account\_id, references(:accounts, on\_delete: :nothing, prefix: @config\_schema)

  end\`
- _# 4. Delete the account\_id column_

  alter table(:users, prefix: @config\_schema) do

  remove :account\_id

  end

2024-10-10 02:39 UTC, thisisgoldman commented on test/sequin/accounts_test.exs
Backend tests are green ✅ LiveView tests as a todo

2024-10-10 03:54 UTC, RTLS requested changes

2024-10-10 03:54 UTC, RTLS commented on lib/sequin_web/components/sidenav.ex
> +        {:reply, %{error: "Failed to create account"}, socket}
the changeset has errors you can use. propagate to users so they know what's wrong

2024-10-10 03:54 UTC, RTLS commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: "Failed to rename account. The name is too long."}, socket}
ditto

2024-10-10 03:54 UTC, RTLS commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: "Cannot delete account if this is your only account"}, socket}
ditto?

2024-10-10 03:54 UTC, RTLS commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: "Cannot delete account if this is your only account"}, socket}
`Sequin.Changeset.errors_on/1`

2024-10-10 03:54 UTC, RTLS commented on lib/sequin_web/live_helpers.ex
>    end
maybe make this resilient to user being nil as in current_account/1 above

2024-10-10 03:54 UTC, RTLS commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +    end
this will fail if any of the account_id values are null

we should use sql query to set the null ones to the current default account from accounts_users before we add this constraint back in, thank you claude

2024-10-10 03:54 UTC, RTLS commented on test/sequin/accounts_test.exs
> +      account = user.id |> Accounts.list_accounts_for_user() |> List.first()
```suggestion
      account = Accounts.list_accounts_for_user(user.id) |> Enum.find(& &1.default)
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/user.ex
> +      end
```suggestion
    user = Sequin.Repo.preload(user, [:accounts_users, :accounts])
```

Repo.preload will do nothing if they are already loaded

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/user.ex
> +        |> Enum.sort_by(& &1.inserted_at)
sort_by date!!!!

https://hexdocs.pm/elixir/1.12/Enum.html#sort/2

```
        |> Enum.sort_by(& &1.inserted_at, {:asc, DateTime})
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +  def get_user_with_accounts_and_account_users!(user_id) do
```suggestion
  def get_user_with_preloads!(user_id) do
```

????

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
>    end
```
  def get_impersonated_account_id(user, token) do
    user_id = user.id

    case UserToken.verify_session_token_query(token, "impersonate") do
      {:ok, query} ->
        case Repo.one(query) do
          {%User{id: ^user_id}, account_id} -> {:ok, account_id}
          _ -> :error
        end
    end
  end
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
>    end
very important!

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +  end
we want to list accounts not accounts_users

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +  end
join accounts to users through account_users

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +    end
when you implement above, you can simplify this one to use that

```
account_id
|> Account.where_id()
|> Account.where_user_id(user_id)
|> Repo.one
|> case do
  nil -> {:error, not found}
  account -> {:ok, account}
end
```

```account.ex
  def where_user_id(query \\ base_query(), user_id) do
    from(a in query, as: :account, where: a.id == ^user_id)
  end

  defp base_query(query \\ __MODULE__) do
    from(a in query, as: :account)
  end
```

this is broken because you have to join but this is the right idea

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +    end
```suggestion
  def delete_account(%Account{} = account) do
    affected_users = list_users_for_account(account.id)
    |> Repo.preload([:accounts_users, :accounts])
    
    if Enum.any?(affected_users, &length(&1.accounts) == 1) do
      {:error,
       Error.invariant(message: "cannot delete account because it is the last remaining account for one or more users")}
    else
      Repo.delete(account)
    end
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +  def delete_account_and_account_resources(%Account{} = account, delete_users \\ false) do
```suggestion
  def delete_account_and_account_resources(%Account{} = account, opts \\ []) do
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +      if delete_users do
```suggestion
      if opts[:delete_users] do
```

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +      if delete_users do
`delete_users: true`

2024-10-10 03:54 UTC, RTLS commented on lib/sequin/accounts/accounts.ex
> +        {:error, Error.not_found(entity: :account)}
```suggestion
    case get_account(account.id) do
      {:ok, account} ->
```

2024-10-10 18:58 UTC, acco commented on assets/svelte/components/Sidenav.svelte
> +              size="settings"
menu

2024-10-10 18:58 UTC, acco commented on assets/svelte/components/Sidenav.svelte
> +              size="settings"
menu

2024-10-10 18:58 UTC, acco commented on assets/svelte/settings/AccountSettings.svelte
> +      >
remove

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/account.ex
> +    |> validate_length(:name, max: 80, message: "Account name cannot be longer than 80 characters")
```suggestion
    |> validate_length(:name, max: 80)
```

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/account.ex
> +  end
rm

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +  def delete_account_and_account_resources(%Account{} = account, opts \\ [delete_users: false]) do
```suggestion
  def delete_account_and_account_resources(%Account{} = account, opts \\ []) do
```

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      if Keyword.get(opts, :delete_users, true) do
```suggestion
      if opts[:delete_users] do
```

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      {:ok, _account} ->
```
with {:ok, account} <- get_account(account.id)
```

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +        end
rm

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +          |> Repo.get_by(user_id: user_id, account_id: account_id)
account_user

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/accounts.ex
> +      _account_user ->
```suggestion
      account_user ->
```

2024-10-10 18:58 UTC, acco commented on lib/sequin/accounts/user.ex
> +        |> List.first()
Enum.min_by(& &1.inserted_at, DateTime)

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +        {:reply, %{error: Error.ValidationError.message(error)}, socket}
```suggestion
        {:reply, %{error: Exception.message(error)}, socket}
```

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/components/sidenav.ex
> +    end
rm

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: Error.ValidationError.message(error)}, socket}
```suggestion
        {:reply, %{error: Exception.message(error)}, socket}
```

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: error.message}, socket}
```suggestion
        {:reply, %{error: Exception.message(error)}, socket}
```

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +        {:reply, %{error: Error.ValidationError.message(error)}, socket}
```suggestion
        {:reply, %{error: Exception.message(error)}, socket}
```

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live/settings/account_settings_live.ex
> +    assigns = assign(assigns, :current_account, User.current_account(assigns.current_user))
```suggestion
    assigns = assign(assigns, :parent_id, "account_settings")
    |> assign(:current_account, User.current_account(assigns.current_user))
```

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live_helpers.ex
> +      user && User.current_account(user)
Try removing safety from all?

2024-10-10 18:58 UTC, acco commented on lib/sequin_web/live_helpers.ex
> +        current_account && current_account.id
```suggestion
        current_account.id
```

2024-10-10 18:58 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +defmodule Sequin.Repo.Migrations.CreateUsersAccountsAndModifyUsers do
```suggestion
defmodule Sequin.Repo.Migrations.CreateAccountsUsersAndModifyUsers do
```

2024-10-10 18:58 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +defmodule Sequin.Repo.Migrations.CreateUsersAccountsAndModifyUsers do
rename file

2024-10-10 18:58 UTC, acco commented on priv/repo/migrations/20241003014334_create_users_accounts_and_modify_users_for_many_accounts.exs
> +    create unique_index(:accounts_users, [:user_id, :current],
```suggestion
    create unique_index(:accounts_users, [:user_id],
```

2024-10-10 18:58 UTC, acco commented on test/sequin/accounts_test.exs
> +      Accounts.set_current_account_for_user(user.id, account_2.id)
{:ok, _} =

2024-10-10 18:58 UTC, acco commented on test/sequin/accounts_test.exs
> +        |> Enum.sort_by(& &1.inserted_at)
```suggestion
        |> Enum.sort_by(& &1.inserted_at, DateTime)
```

2024-10-10 20:40 UTC, thisisgoldman commented
### Merge activity

* **Oct 10, 4:40 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/sequinstream/sequin/364).

2024-10-10 20:41 UTC, merged