feature: add support for GCP pub sub emulator sink
sequinstream/sequin pull request #794
Opened 2024-12-31 23:18 UTC by girishramnani

- Add the `use emulator` switch for sink
- Add the `connection url` input when selected the `use emulator` switch
- Use the connection url in the pub sub client

Overall providing support for the GCP PubSub Emulator in the sink.

2025-01-01 00:36 UTC, acco requested changes
Great work, @girishramnani! Impressed with the thoroughness here.

See comments in-line. If you can, sign off your PR with `make signoff` - see instructions in [CONTRIBUTING.md](https://github.com/sequinstream/sequin/blob/main/CONTRIBUTING.md)

Please test to make sure it works with an emulator GCP. Also, make sure both creates and edits work (and that during edits, you can switch emulator on/off)

Also, might make sense to add a test to `test/sequin/gcp_pubsub_test.exs`? Ask Claude Sonnet to help :)

2025-01-01 00:36 UTC, acco commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +      <Label for="use-emulator" class="align-text-top">Use Emulator</Label>
Can you add an info popover here that describes what the emulator is? You can see examples of info popovers elsewhere in the codebase. The copy:

`The GCP Pub/Sub emulator lets you run Pub/Sub locally for dev and testing purposes. [Learn more](https://cloud.google.com/pubsub/docs/emulator)`

Learn more should be a target=_blank link

2025-01-01 00:36 UTC, acco commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +          placeholder="0.0.0.0:8432"
```suggestion
          placeholder="localhost:8432"
```

2025-01-01 00:36 UTC, acco commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +        </p>
```suggestion
```

2025-01-01 00:36 UTC, acco commented on assets/svelte/types/consumer.ts
> +    connection_url: string;
```suggestion
    emulator_base_url: string;
```

2025-01-01 00:36 UTC, acco commented on lib/sequin/consumers/gcp_pubsub_sink.ex
> +    use_emulator? = get_change(changeset, :use_emulator)
```suggestion
    use_emulator? = get_field(changeset, :use_emulator)
```

2025-01-01 00:36 UTC, acco commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +    {/if}
Should we hide credentials field below when the emulator is enabled? If it's unused, we should hide it.

2025-01-01 00:36 UTC, acco commented on lib/sequin/transforms/transforms.ex
> +      connection_url: sink.connection_url,
Nice, thanks for adding in all places!

2025-01-01 00:36 UTC, acco commented on assets/svelte/types/consumer.ts
> +    connection_url: string;
Please make this change everywhere below

2025-01-01 00:36 UTC, acco commented on lib/sequin/sinks/gcp/pubsub.ex
> +    pubsub_base_url = get_pubsub_base_url(client)
I think you can do this in-line:

```suggestion
    base_url = Map.get(client.req_opts, :base_url, @pubsub_base_url)
```

2025-01-01 00:36 UTC, acco commented on lib/sequin/sinks/gcp/pubsub.ex
> +    if is_nil(base_url) do
Right now, this uses the presence of `base_url` in `req_opts` to determine if we should add auth headers.

How about instead we just only add auth headers if `Client.credentials` is not `nil`?

2025-01-01 00:36 UTC, acco commented on lib/sequin/sinks/gcp/pubsub.ex
> +    if is_nil(base_url) do
Below, in `authenticated_request`, you can do:

```elixir
headers = [{"content-type", "application/json"}] |> maybe_put_auth_headers(client)
```

2025-01-01 00:38 UTC, girishramnani commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +  }
Removed already

2025-01-01 00:41 UTC, girishramnani commented on lib/sequin/sinks/gcp/pubsub.ex
> +    if is_nil(base_url) do
Someone might just keep the credentials.
Imagine a user flow.
They added the pub sub details and that didn’t work - so they selected the emulator but never removed to credentials.

2025-01-01 00:41 UTC, girishramnani commented on assets/svelte/consumers/SinkGcpPubsubForm.svelte
> +    {/if}
Yeah good idea

2025-01-01 00:46 UTC, acco commented on lib/sequin/sinks/gcp/pubsub.ex
> +    if is_nil(base_url) do
@girishramnani That's a good point. In that case, I think we should nilify the credentials - perhaps in the `conditional_` changeset function you added?

That way, there aren't credentials "hidden" in the sink. Would be surprising later to edit the sink, turn off the emulator, and see that there were credentials in there the whole time!

Basically, just trying to have as few things know about the emulator/base URL as possible

2025-01-01 00:48 UTC, girishramnani commented on lib/sequin/sinks/gcp/pubsub.ex
> +    if is_nil(base_url) do
Yeah that would be best

2025-01-13 22:26 UTC, acco commented
@girishramnani Checking back on this one – did you end up completing and QA'ing? Happy to take another look and merge if it's ready

2025-01-15 17:47 UTC, acco commented
* **#794** <a href="https://app.graphite.dev/github/pr/sequinstream/sequin/794?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/sequinstream/sequin/794?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-15 19:03 UTC, closed without merging

2025-01-15 19:04 UTC, acco commented
Merged in https://github.com/sequinstream/sequin/pull/876/files

Thanks for kicking off, @girishramnani